source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

platform :ios, '8.0'

target 'SSIDCard_Example' do
  pod 'SSIDCard', :path => '../'

  target 'SSIDCard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
